#ifndef SFE_SARA_R5_LIBRARY_H
#define SFE_SARA_R5_LIBRARY_H

#include "sfe_ublox_at_commands.h"

// RegEx Replace: \#define\sSARA\_R5\_([A-Z0-9_]+).* \#define SARA\_R5\_$+ UBLOX\_AT\_$+

#define SARA_R5_POWER_PIN -1 // Default to no pin
#define SARA_R5_RESET_PIN -1

// Timing
#define SARA_R5_STANDARD_RESPONSE_TIMEOUT 1000
#define SARA_R5_10_SEC_TIMEOUT 10000
#define SARA_R5_55_SECS_TIMEOUT 55000
#define SARA_R5_2_MIN_TIMEOUT 120000
#define SARA_R5_3_MIN_TIMEOUT 180000
#define SARA_R5_SET_BAUD_TIMEOUT 500
#define SARA_R5_POWER_OFF_PULSE_PERIOD 3200 // Hold PWR_ON low for this long to power the module off
#define SARA_R5_POWER_ON_PULSE_PERIOD 100 // Hold PWR_ON low for this long to power the module on (SARA-R510M8S)
#define SARA_R5_RESET_PULSE_PERIOD 23000 // Used to perform an abrupt emergency hardware shutdown. 23 seconds... (Yes, really!)
#define SARA_R5_POWER_OFF_TIMEOUT 40000 // Datasheet says 40 seconds...
#define SARA_R5_IP_CONNECT_TIMEOUT 130000
#define SARA_R5_POLL_DELAY 1
#define SARA_R5_SOCKET_WRITE_TIMEOUT 10000

// ## Suported AT Commands
// ### General
const char SARA_R5_COMMAND_AT[] = "AT";           // AT "Test"
const char SARA_R5_COMMAND_ECHO[] = "E";          // Local Echo
const char SARA_R5_COMMAND_MANU_ID[] = "+CGMI";   // Manufacturer identification
const char SARA_R5_COMMAND_MODEL_ID[] = "+CGMM";  // Model identification
const char SARA_R5_COMMAND_FW_VER_ID[] = "+CGMR"; // Firmware version identification
const char SARA_R5_COMMAND_SERIAL_NO[] = "+CGSN"; // Product serial number
const char SARA_R5_COMMAND_IMEI[] = "+GSN";       // IMEI identification
const char SARA_R5_COMMAND_IMSI[] = "+CIMI";      // IMSI identification
const char SARA_R5_COMMAND_CCID[] = "+CCID";      // SIM CCID
const char SARA_R5_COMMAND_REQ_CAP[] = "+GCAP";   // Request capabilities list
// ### Control and status
const char SARA_R5_COMMAND_POWER_OFF[] = "+CPWROFF"; // Module switch off
const char SARA_R5_COMMAND_FUNC[] = "+CFUN";         // Functionality (reset, etc.)
const char SARA_R5_COMMAND_CLOCK[] = "+CCLK";        // Real-time clock
const char SARA_R5_COMMAND_AUTO_TZ[] = "+CTZU";      // Automatic time zone update
const char SARA_R5_COMMAND_TZ_REPORT[] = "+CTZR";    // Time zone reporting
// ### Network service
const char SARA_R5_COMMAND_CNUM[] = "+CNUM"; // Subscriber number
const char SARA_R5_SIGNAL_QUALITY[] = "+CSQ";
const char SARA_R5_EXT_SIGNAL_QUALITY[] = "+CESQ";
const char SARA_R5_OPERATOR_SELECTION[] = "+COPS";
const char SARA_R5_REGISTRATION_STATUS[] = "+CREG";
const char SARA_R5_EPSREGISTRATION_STATUS[] = "+CEREG";
const char SARA_R5_READ_OPERATOR_NAMES[] = "+COPN";
const char SARA_R5_COMMAND_MNO[] = "+UMNOPROF"; // MNO (mobile network operator) Profile
// ### SIM
const char SARA_R5_SIM_STATE[] = "+USIMSTAT";
const char SARA_R5_COMMAND_SIMPIN[] = "+CPIN";    // SIM PIN
// ### SMS
const char SARA_R5_MESSAGE_FORMAT[] = "+CMGF";     // Set SMS message format
const char SARA_R5_SEND_TEXT[] = "+CMGS";          // Send SMS message
const char SARA_R5_NEW_MESSAGE_IND[] = "+CNMI";    // New [SMS] message indication
const char SARA_R5_PREF_MESSAGE_STORE[] = "+CPMS"; // Preferred message storage
const char SARA_R5_READ_TEXT_MESSAGE[] = "+CMGR";  // Read message
const char SARA_R5_DELETE_MESSAGE[] = "+CMGD";     // Delete message
// V24 control and V25ter (UART interface)
const char SARA_R5_FLOW_CONTROL[] = "&K";   // Flow control
const char SARA_R5_COMMAND_BAUD[] = "+IPR"; // Baud rate
// ### Packet switched data services
const char SARA_R5_MESSAGE_PDP_DEF[] = "+CGDCONT";            // Packet switched Data Profile context definition
const char SARA_R5_MESSAGE_PDP_CONFIG[] = "+UPSD";            // Packet switched Data Profile configuration
const char SARA_R5_MESSAGE_PDP_ACTION[] = "+UPSDA";           // Perform the action for the specified PSD profile
const char SARA_R5_MESSAGE_PDP_CONTEXT_ACTIVATE[] = "+CGACT"; // Activates or deactivates the specified PDP context
const char SARA_R5_MESSAGE_ENTER_PPP[] = "D";
const char SARA_R5_NETWORK_ASSIGNED_DATA[] = "+UPSND";        // Packet switched network-assigned data
// ### GPIO
const char SARA_R5_COMMAND_GPIO[] = "+UGPIOC"; // GPIO Configuration
// ### IP
const char SARA_R5_CREATE_SOCKET[] = "+USOCR";      // Create a new socket
const char SARA_R5_CLOSE_SOCKET[] = "+USOCL";       // Close a socket
const char SARA_R5_CONNECT_SOCKET[] = "+USOCO";     // Connect to server on socket
const char SARA_R5_WRITE_SOCKET[] = "+USOWR";       // Write data to a socket
const char SARA_R5_WRITE_UDP_SOCKET[] = "+USOST";   // Write data to a UDP socket
const char SARA_R5_READ_SOCKET[] = "+USORD";        // Read from a socket
const char SARA_R5_READ_UDP_SOCKET[] = "+USORF";    // Read UDP data from a socket
const char SARA_R5_LISTEN_SOCKET[] = "+USOLI";      // Listen for connection on socket
const char SARA_R5_GET_ERROR[] = "+USOER";          // Get last socket error.
const char SARA_R5_SOCKET_DIRECT_LINK[] = "+USODL"; // Set socket in Direct Link mode
const char SARA_R5_SOCKET_CONTROL[] = "+USOCTL";    // Query the socket parameters
const char SARA_R5_UD_CONFIGURATION[] = "+UDCONF";  // User Datagram Configuration
// ### Ping
const char SARA_R5_PING_COMMAND[] = "+UPING"; // Ping
// ### HTTP
const char SARA_R5_HTTP_PROFILE[] = "+UHTTP";          // Configure the HTTP profile. Up to 4 different profiles can be defined
const char SARA_R5_HTTP_COMMAND[] = "+UHTTPC";         // Trigger the specified HTTP command
const char SARA_R5_HTTP_PROTOCOL_ERROR[] = "+UHTTPER"; // Retrieves the error class and code of the latest HTTP operation on the specified HTTP profile.

const char SARA_R5_MQTT_NVM[] = "+UMQTTNV";
const char SARA_R5_MQTT_PROFILE[] = "+UMQTT";
const char SARA_R5_MQTT_COMMAND[] = "+UMQTTC";
const char SARA_R5_MQTT_PROTOCOL_ERROR[] = "+UMQTTER";
// ### FTP
const char SARA_R5_FTP_PROFILE[] = "+UFTP";
const char SARA_R5_FTP_COMMAND[] = "+UFTPC";
const char SARA_R5_FTP_PROTOCOL_ERROR[] = "+UFTPER";
// ### GNSS
const char SARA_R5_GNSS_POWER[] = "+UGPS";                   // GNSS power management configuration
const char SARA_R5_GNSS_ASSISTED_IND[] = "+UGIND";           // Assisted GNSS unsolicited indication
const char SARA_R5_GNSS_REQUEST_LOCATION[] = "+ULOC";        // Ask for localization information
const char SARA_R5_GNSS_GPRMC[] = "+UGRMC";                  // Ask for localization information
const char SARA_R5_GNSS_REQUEST_TIME[] = "+UTIME";           // Ask for time information from cellular modem (CellTime)
const char SARA_R5_GNSS_TIME_INDICATION[] = "+UTIMEIND";     // Time information request status unsolicited indication
const char SARA_R5_GNSS_TIME_CONFIGURATION[] = "+UTIMECFG";  // Sets time configuration
const char SARA_R5_GNSS_CONFIGURE_SENSOR[] = "+ULOCGNSS";    // Configure GNSS sensor
const char SARA_R5_GNSS_CONFIGURE_LOCATION[] = "+ULOCCELL";  // Configure cellular location sensor (CellLocate®)
const char SARA_R5_AIDING_SERVER_CONFIGURATION[] = "+UGSRV"; // Configure aiding server (CellLocate®)
// ### File System
// TO DO: Add support for file tags. Default tag to USER
const char SARA_R5_FILE_SYSTEM_READ_FILE[] = "+URDFILE";      // Read a file
const char SARA_R5_FILE_SYSTEM_READ_BLOCK[] = "+URDBLOCK";      // Read a block from a file
const char SARA_R5_FILE_SYSTEM_DOWNLOAD_FILE[] = "+UDWNFILE";    // Download a file into the module
const char SARA_R5_FILE_SYSTEM_LIST_FILES[] = "+ULSTFILE";    // List of files, size of file, etc.
const char SARA_R5_FILE_SYSTEM_DELETE_FILE[] = "+UDELFILE";   // Delete a file
// ### File System
// TO DO: Add support for file tags. Default tag to USER
const char SARA_R5_SEC_PROFILE[] = "+USECPRF";
const char SARA_R5_SEC_MANAGER[] = "+USECMNG";


// ### URC strings
const char SARA_R5_READ_SOCKET_URC[] = "+UUSORD:";
const char SARA_R5_READ_UDP_SOCKET_URC[] = "+UUSORF:";
const char SARA_R5_LISTEN_SOCKET_URC[] = "+UUSOLI:";
const char SARA_R5_CLOSE_SOCKET_URC[] = "+UUSOCL:";
const char SARA_R5_GNSS_REQUEST_LOCATION_URC[] = "+UULOC:";
const char SARA_R5_SIM_STATE_URC[] = "+UUSIMSTAT:";
const char SARA_R5_MESSAGE_PDP_ACTION_URC[] = "+UUPSDA:";
const char SARA_R5_HTTP_COMMAND_URC[] = "+UUHTTPCR:";
const char SARA_R5_MQTT_COMMAND_URC[] = "+UUMQTTC:";
const char SARA_R5_PING_COMMAND_URC[] = "+UUPING:";
const char SARA_R5_REGISTRATION_STATUS_URC[] = "+CREG:";
const char SARA_R5_EPSREGISTRATION_STATUS_URC[] = "+CEREG:";
const char SARA_R5_FTP_COMMAND_URC[] = "+UUFTPCR:";

// ### Response
const char SARA_R5_RESPONSE_MORE[] = "\n>";
const char SARA_R5_RESPONSE_OK[] = "\nOK\r\n";
const char SARA_R5_RESPONSE_ERROR[] = "\nERROR\r\n";
const char SARA_R5_RESPONSE_CONNECT[] = "\r\nCONNECT\r\n";
#define SARA_R5_RESPONSE_OK_OR_ERROR nullptr

#define SARA_R5_NUM_SOCKETS 6

#define SARA_R5_NUM_SUPPORTED_BAUD 6
const unsigned long SARA_R5_SUPPORTED_BAUD[SARA_R5_NUM_SUPPORTED_BAUD] =
    {
        115200,
        9600,
        19200,
        38400,
        57600,
        230400};
#define SARA_R5_DEFAULT_BAUD_RATE 115200

// Flow control definitions for AT&K
// Note: SW (XON/XOFF) flow control is not supported on the SARA_R5
#define SARA_R5_DISABLE_FLOW_CONTROL UBLOX_AT_DISABLE_FLOW_CONTROL
#define SARA_R5_ENABLE_FLOW_CONTROL UBLOX_AT_ENABLE_FLOW_CONTROL

#define SARA_R5_ERROR_INVALID UBLOX_AT_ERROR_INVALID
#define SARA_R5_ERROR_SUCCESS UBLOX_AT_ERROR_SUCCESS
#define SARA_R5_ERROR_OUT_OF_MEMORY UBLOX_AT_ERROR_OUT_OF_MEMORY
#define SARA_R5_ERROR_TIMEOUT UBLOX_AT_ERROR_TIMEOUT
#define SARA_R5_ERROR_UNEXPECTED_PARAM UBLOX_AT_ERROR_UNEXPECTED_PARAM
#define SARA_R5_ERROR_UNEXPECTED_RESPONSE UBLOX_AT_ERROR_UNEXPECTED_RESPONSE
#define SARA_R5_ERROR_NO_RESPONSE UBLOX_AT_ERROR_NO_RESPONSE
#define SARA_R5_ERROR_DEREGISTERED UBLOX_AT_ERROR_DEREGISTERED
#define SARA_R5_ERROR_ZERO_READ_LENGTH UBLOX_AT_ERROR_ZERO_READ_LENGTH
#define SARA_R5_ERROR_ERROR UBLOX_AT_ERROR_ERROR
#define SARA_R5_SUCCESS SARA_R5_ERROR_SUCCESS

#define SARA_R5_REGISTRATION_INVALID UBLOX_AT_REGISTRATION_INVALID
#define SARA_R5_REGISTRATION_NOT_REGISTERED UBLOX_AT_REGISTRATION_NOT_REGISTERED
#define SARA_R5_REGISTRATION_HOME UBLOX_AT_REGISTRATION_HOME
#define SARA_R5_REGISTRATION_SEARCHING UBLOX_AT_REGISTRATION_SEARCHING
#define SARA_R5_REGISTRATION_DENIED UBLOX_AT_REGISTRATION_DENIED
#define SARA_R5_REGISTRATION_UNKNOWN UBLOX_AT_REGISTRATION_UNKNOWN
#define SARA_R5_REGISTRATION_ROAMING UBLOX_AT_REGISTRATION_ROAMING
#define SARA_R5_REGISTRATION_HOME_SMS_ONLY UBLOX_AT_REGISTRATION_HOME_SMS_ONLY
#define SARA_R5_REGISTRATION_ROAMING_SMS_ONLY UBLOX_AT_REGISTRATION_ROAMING_SMS_ONLY
#define SARA_R5_REGISTRATION_EMERGENCY_SERV_ONLY UBLOX_AT_REGISTRATION_EMERGENCY_SERV_ONLY
#define SARA_R5_REGISTRATION_HOME_CSFB_NOT_PREFERRED UBLOX_AT_REGISTRATION_HOME_CSFB_NOT_PREFERRED
#define SARA_R5_REGISTRATION_ROAMING_CSFB_NOT_PREFERRED UBLOX_AT_REGISTRATION_ROAMING_CSFB_NOT_PREFERRED

#define SARA_R5_TCP UBLOX_AT_TCP
#define SARA_R5_UDP UBLOX_AT_UDP

#define SARA_R5_TCP_SOCKET_STATUS_INACTIVE UBLOX_AT_TCP_SOCKET_STATUS_INACTIVE
#define SARA_R5_TCP_SOCKET_STATUS_LISTEN UBLOX_AT_TCP_SOCKET_STATUS_LISTEN
#define SARA_R5_TCP_SOCKET_STATUS_SYN_SENT UBLOX_AT_TCP_SOCKET_STATUS_SYN_SENT
#define SARA_R5_TCP_SOCKET_STATUS_SYN_RCVD UBLOX_AT_TCP_SOCKET_STATUS_SYN_RCVD
#define SARA_R5_TCP_SOCKET_STATUS_ESTABLISHED UBLOX_AT_TCP_SOCKET_STATUS_ESTABLISHED
#define SARA_R5_TCP_SOCKET_STATUS_FIN_WAIT_1 UBLOX_AT_TCP_SOCKET_STATUS_FIN_WAIT_1
#define SARA_R5_TCP_SOCKET_STATUS_FIN_WAIT_2 UBLOX_AT_TCP_SOCKET_STATUS_FIN_WAIT_2
#define SARA_R5_TCP_SOCKET_STATUS_CLOSE_WAIT UBLOX_AT_TCP_SOCKET_STATUS_CLOSE_WAIT
#define SARA_R5_TCP_SOCKET_STATUS_CLOSING UBLOX_AT_TCP_SOCKET_STATUS_CLOSING
#define SARA_R5_TCP_SOCKET_STATUS_LAST_ACK UBLOX_AT_TCP_SOCKET_STATUS_LAST_ACK
#define SARA_R5_TCP_SOCKET_STATUS_TIME_WAIT UBLOX_AT_TCP_SOCKET_STATUS_TIME_WAIT

#define SARA_R5_MESSAGE_FORMAT_PDU UBLOX_AT_MESSAGE_FORMAT_PDU
#define SARA_R5_MESSAGE_FORMAT_TEXT UBLOX_AT_MESSAGE_FORMAT_TEXT

#define SARA_R5_UTIME_MODE_STOP UBLOX_AT_UTIME_MODE_STOP
#define SARA_R5_UTIME_MODE_PPS UBLOX_AT_UTIME_MODE_PPS
#define SARA_R5_UTIME_MODE_ONE_SHOT UBLOX_AT_UTIME_MODE_ONE_SHOT
#define SARA_R5_UTIME_MODE_EXT_INT UBLOX_AT_UTIME_MODE_EXT_INT

#define SARA_R5_UTIME_SENSOR_NONE UBLOX_AT_UTIME_SENSOR_NONE
#define SARA_R5_UTIME_SENSOR_GNSS_LTE UBLOX_AT_UTIME_SENSOR_GNSS_LTE
#define SARA_R5_UTIME_SENSOR_LTE UBLOX_AT_UTIME_SENSOR_LTE

#define SARA_R5_UTIME_URC_CONFIGURATION_DISABLED UBLOX_AT_UTIME_URC_CONFIGURATION_DISABLED
#define SARA_R5_UTIME_URC_CONFIGURATION_ENABLED UBLOX_AT_UTIME_URC_CONFIGURATION_ENABLED

#define SARA_R5_SIM_NOT_PRESENT UBLOX_AT_SIM_NOT_PRESENT
#define SARA_R5_SIM_PIN_NEEDED UBLOX_AT_SIM_PIN_NEEDED
#define SARA_R5_SIM_PIN_BLOCKED UBLOX_AT_SIM_PIN_BLOCKED
#define SARA_R5_SIM_PUK_BLOCKED UBLOX_AT_SIM_PUK_BLOCKED
#define SARA_R5_SIM_NOT_OPERATIONAL UBLOX_AT_SIM_NOT_OPERATIONAL
#define SARA_R5_SIM_RESTRICTED UBLOX_AT_SIM_RESTRICTED
#define SARA_R5_SIM_OPERATIONAL UBLOX_AT_SIM_OPERATIONAL
//SARA_R5_SIM_PHONEBOOK_READY, // Not reported by SARA-R5
//SARA_R5_SIM_USIM_PHONEBOOK_READY, // Not reported by SARA-R5
//SARA_R5_SIM_TOOLKIT_REFRESH_SUCCESSFUL, // Not reported by SARA-R5
//SARA_R5_SIM_TOOLKIT_REFRESH_UNSUCCESSFUL, // Not reported by SARA-R5
//SARA_R5_SIM_PPP_CONNECTION_ACTIVE, // Not reported by SARA-R5
//SARA_R5_SIM_VOICE_CALL_ACTIVE, // Not reported by SARA-R5
//SARA_R5_SIM_CSD_CALL_ACTIVE // Not reported by SARA-R5

#define SARA_R5_NUM_PSD_PROFILES 6             // Number of supported PSD profiles
#define SARA_R5_NUM_PDP_CONTEXT_IDENTIFIERS 11 // Number of supported PDP context identifiers
#define SARA_R5_NUM_HTTP_PROFILES 4            // Number of supported HTTP profiles

#define SARA_R5_HTTP_OP_CODE_SERVER_IP UBLOX_AT_HTTP_OP_CODE_SERVER_IP
#define SARA_R5_HTTP_OP_CODE_SERVER_NAME UBLOX_AT_HTTP_OP_CODE_SERVER_NAME
#define SARA_R5_HTTP_OP_CODE_USERNAME UBLOX_AT_HTTP_OP_CODE_USERNAME
#define SARA_R5_HTTP_OP_CODE_PASSWORD UBLOX_AT_HTTP_OP_CODE_PASSWORD
#define SARA_R5_HTTP_OP_CODE_AUTHENTICATION UBLOX_AT_HTTP_OP_CODE_AUTHENTICATION
#define SARA_R5_HTTP_OP_CODE_SERVER_PORT UBLOX_AT_HTTP_OP_CODE_SERVER_PORT
#define SARA_R5_HTTP_OP_CODE_SECURE UBLOX_AT_HTTP_OP_CODE_SECURE
#define SARA_R5_HTTP_OP_CODE_REQUEST_TIMEOUT UBLOX_AT_HTTP_OP_CODE_REQUEST_TIMEOUT
#define SARA_R5_HTTP_OP_CODE_ADD_CUSTOM_HEADERS UBLOX_AT_HTTP_OP_CODE_ADD_CUSTOM_HEADERS

#define SARA_R5_HTTP_COMMAND_HEAD UBLOX_AT_HTTP_COMMAND_HEAD
#define SARA_R5_HTTP_COMMAND_GET UBLOX_AT_HTTP_COMMAND_GET
#define SARA_R5_HTTP_COMMAND_DELETE UBLOX_AT_HTTP_COMMAND_DELETE
#define SARA_R5_HTTP_COMMAND_PUT UBLOX_AT_HTTP_COMMAND_PUT
#define SARA_R5_HTTP_COMMAND_POST_FILE UBLOX_AT_HTTP_COMMAND_POST_FILE
#define SARA_R5_HTTP_COMMAND_POST_DATA UBLOX_AT_HTTP_COMMAND_POST_DATA
#define SARA_R5_HTTP_COMMAND_GET_FOTA UBLOX_AT_HTTP_COMMAND_GET_FOTA

#define SARA_R5_HTTP_CONTENT_APPLICATION_X_WWW UBLOX_AT_HTTP_CONTENT_APPLICATION_X_WWW
#define SARA_R5_HTTP_CONTENT_TEXT_PLAIN UBLOX_AT_HTTP_CONTENT_TEXT_PLAIN
#define SARA_R5_HTTP_CONTENT_APPLICATION_OCTET UBLOX_AT_HTTP_CONTENT_APPLICATION_OCTET
#define SARA_R5_HTTP_CONTENT_MULTIPART_FORM UBLOX_AT_HTTP_CONTENT_MULTIPART_FORM
#define SARA_R5_HTTP_CONTENT_APPLICATION_JSON UBLOX_AT_HTTP_CONTENT_APPLICATION_JSON
#define SARA_R5_HTTP_CONTENT_APPLICATION_XML UBLOX_AT_HTTP_CONTENT_APPLICATION_XML
#define SARA_R5_HTTP_CONTENT_USER_DEFINED UBLOX_AT_HTTP_CONTENT_USER_DEFINED

#define SARA_R5_MQTT_NV_RESTORE UBLOX_AT_MQTT_NV_RESTORE
#define SARA_R5_MQTT_NV_SET UBLOX_AT_MQTT_NV_SET
#define SARA_R5_MQTT_NV_STORE UBLOX_AT_MQTT_NV_STORE

#define SARA_R5_MQTT_PROFILE_CLIENT_ID UBLOX_AT_MQTT_PROFILE_CLIENT_ID
#define SARA_R5_MQTT_PROFILE_SERVERNAME UBLOX_AT_MQTT_PROFILE_SERVERNAME
#define SARA_R5_MQTT_PROFILE_IPADDRESS UBLOX_AT_MQTT_PROFILE_IPADDRESS
#define SARA_R5_MQTT_PROFILE_USERNAMEPWD UBLOX_AT_MQTT_PROFILE_USERNAMEPWD
#define SARA_R5_MQTT_PROFILE_QOS UBLOX_AT_MQTT_PROFILE_QOS
#define SARA_R5_MQTT_PROFILE_RETAIN UBLOX_AT_MQTT_PROFILE_RETAIN
#define SARA_R5_MQTT_PROFILE_TOPIC UBLOX_AT_MQTT_PROFILE_TOPIC
#define SARA_R5_MQTT_PROFILE_MESSAGE UBLOX_AT_MQTT_PROFILE_MESSAGE
#define SARA_R5_MQTT_PROFILE_INACTIVITYTIMEOUT UBLOX_AT_MQTT_PROFILE_INACTIVITYTIMEOUT
#define SARA_R5_MQTT_PROFILE_SECURE UBLOX_AT_MQTT_PROFILE_SECURE

#define SARA_R5_MQTT_COMMAND_INVALID UBLOX_AT_MQTT_COMMAND_INVALID
#define SARA_R5_MQTT_COMMAND_LOGOUT UBLOX_AT_MQTT_COMMAND_LOGOUT
#define SARA_R5_MQTT_COMMAND_LOGIN UBLOX_AT_MQTT_COMMAND_LOGIN
#define SARA_R5_MQTT_COMMAND_PUBLISH UBLOX_AT_MQTT_COMMAND_PUBLISH
#define SARA_R5_MQTT_COMMAND_PUBLISHFILE UBLOX_AT_MQTT_COMMAND_PUBLISHFILE
#define SARA_R5_MQTT_COMMAND_SUBSCRIBE UBLOX_AT_MQTT_COMMAND_SUBSCRIBE
#define SARA_R5_MQTT_COMMAND_UNSUBSCRIBE UBLOX_AT_MQTT_COMMAND_UNSUBSCRIBE
#define SARA_R5_MQTT_COMMAND_READ UBLOX_AT_MQTT_COMMAND_READ
#define SARA_R5_MQTT_COMMAND_RCVMSGFORMAT UBLOX_AT_MQTT_COMMAND_RCVMSGFORMAT
#define SARA_R5_MQTT_COMMAND_PING UBLOX_AT_MQTT_COMMAND_PING
#define SARA_R5_MQTT_COMMAND_PUBLISHBINARY UBLOX_AT_MQTT_COMMAND_PUBLISHBINARY

#define SARA_R5_FTP_PROFILE_IPADDRESS UBLOX_AT_FTP_PROFILE_IPADDRESS
#define SARA_R5_FTP_PROFILE_SERVERNAME UBLOX_AT_FTP_PROFILE_SERVERNAME
#define SARA_R5_FTP_PROFILE_USERNAME UBLOX_AT_FTP_PROFILE_USERNAME
#define SARA_R5_FTP_PROFILE_PWD UBLOX_AT_FTP_PROFILE_PWD
#define SARA_R5_FTP_PROFILE_ACCOUNT UBLOX_AT_FTP_PROFILE_ACCOUNT
#define SARA_R5_FTP_PROFILE_TIMEOUT UBLOX_AT_FTP_PROFILE_TIMEOUT
#define SARA_R5_FTP_PROFILE_MODE UBLOX_AT_FTP_PROFILE_MODE

#define SARA_R5_FTP_COMMAND_INVALID UBLOX_AT_FTP_COMMAND_INVALID
#define SARA_R5_FTP_COMMAND_LOGOUT UBLOX_AT_FTP_COMMAND_LOGOUT
#define SARA_R5_FTP_COMMAND_LOGIN UBLOX_AT_FTP_COMMAND_LOGIN
#define SARA_R5_FTP_COMMAND_DELETE_FILE UBLOX_AT_FTP_COMMAND_DELETE_FILE
#define SARA_R5_FTP_COMMAND_RENAME_FILE UBLOX_AT_FTP_COMMAND_RENAME_FILE
#define SARA_R5_FTP_COMMAND_GET_FILE UBLOX_AT_FTP_COMMAND_GET_FILE
#define SARA_R5_FTP_COMMAND_PUT_FILE UBLOX_AT_FTP_COMMAND_PUT_FILE
#define SARA_R5_FTP_COMMAND_GET_FILE_DIRECT UBLOX_AT_FTP_COMMAND_GET_FILE_DIRECT
#define SARA_R5_FTP_COMMAND_PUT_FILE_DIRECT UBLOX_AT_FTP_COMMAND_PUT_FILE_DIRECT
#define SARA_R5_FTP_COMMAND_CHANGE_DIR UBLOX_AT_FTP_COMMAND_CHANGE_DIR
#define SARA_R5_FTP_COMMAND_MKDIR UBLOX_AT_FTP_COMMAND_MKDIR
#define SARA_R5_FTP_COMMAND_RMDIR UBLOX_AT_FTP_COMMAND_RMDIR
#define SARA_R5_FTP_COMMAND_DIR_INFO UBLOX_AT_FTP_COMMAND_DIR_INFO
#define SARA_R5_FTP_COMMAND_LS UBLOX_AT_FTP_COMMAND_LS
#define SARA_R5_FTP_COMMAND_GET_FOTA_FILE UBLOX_AT_FTP_COMMAND_GET_FOTA_FILE

#define SARA_R5_PSD_CONFIG_PARAM_PROTOCOL UBLOX_AT_PSD_CONFIG_PARAM_PROTOCOL
#define SARA_R5_PSD_CONFIG_PARAM_APN UBLOX_AT_PSD_CONFIG_PARAM_APN
//SARA_R5_PSD_CONFIG_PARAM_USERNAME, // Not allowed on SARA-R5
//SARA_R5_PSD_CONFIG_PARAM_PASSWORD, // Not allowed on SARA-R5
#define SARA_R5_PSD_CONFIG_PARAM_DNS1 UBLOX_AT_PSD_CONFIG_PARAM_DNS1
#define SARA_R5_PSD_CONFIG_PARAM_DNS2 UBLOX_AT_PSD_CONFIG_PARAM_DNS2
//SARA_R5_PSD_CONFIG_PARAM_AUTHENTICATION, // Not allowed on SARA-R5
//SARA_R5_PSD_CONFIG_PARAM_IP_ADDRESS, // Not allowed on SARA-R5
//SARA_R5_PSD_CONFIG_PARAM_DATA_COMPRESSION, // Not allowed on SARA-R5
//SARA_R5_PSD_CONFIG_PARAM_HEADER_COMPRESSION, // Not allowed on SARA-R5
#define SARA_R5_PSD_CONFIG_PARAM_MAP_TO_CID UBLOX_AT_PSD_CONFIG_PARAM_MAP_TO_CID

#define SARA_R5_PSD_PROTOCOL_IPV4 UBLOX_AT_PSD_PROTOCOL_IPV4
#define SARA_R5_PSD_PROTOCOL_IPV6 UBLOX_AT_PSD_PROTOCOL_IPV6
#define SARA_R5_PSD_PROTOCOL_IPV4V6_V4_PREF UBLOX_AT_PSD_PROTOCOL_IPV4V6_V4_PREF
#define SARA_R5_PSD_PROTOCOL_IPV4V6_V6_PREF UBLOX_AT_PSD_PROTOCOL_IPV4V6_V6_PREF

#define SARA_R5_PSD_ACTION_RESET UBLOX_AT_PSD_ACTION_RESET
#define SARA_R5_PSD_ACTION_STORE UBLOX_AT_PSD_ACTION_STORE
#define SARA_R5_PSD_ACTION_LOAD UBLOX_AT_PSD_ACTION_LOAD
#define SARA_R5_PSD_ACTION_ACTIVATE UBLOX_AT_PSD_ACTION_ACTIVATE
#define SARA_R5_PSD_ACTION_DEACTIVATE UBLOX_AT_PSD_ACTION_DEACTIVATE

#define SARA_R5_SEC_PROFILE_PARAM_CERT_VAL_LEVEL UBLOX_AT_SEC_PROFILE_PARAM_CERT_VAL_LEVEL
#define SARA_R5_SEC_PROFILE_PARAM_TLS_VER UBLOX_AT_SEC_PROFILE_PARAM_TLS_VER
#define SARA_R5_SEC_PROFILE_PARAM_CYPHER_SUITE UBLOX_AT_SEC_PROFILE_PARAM_CYPHER_SUITE
#define SARA_R5_SEC_PROFILE_PARAM_ROOT_CA UBLOX_AT_SEC_PROFILE_PARAM_ROOT_CA
#define SARA_R5_SEC_PROFILE_PARAM_HOSTNAME UBLOX_AT_SEC_PROFILE_PARAM_HOSTNAME
#define SARA_R5_SEC_PROFILE_PARAM_CLIENT_CERT UBLOX_AT_SEC_PROFILE_PARAM_CLIENT_CERT
#define SARA_R5_SEC_PROFILE_PARAM_CLIENT_KEY UBLOX_AT_SEC_PROFILE_PARAM_CLIENT_KEY
#define SARA_R5_SEC_PROFILE_PARAM_CLIENT_KEY_PWD UBLOX_AT_SEC_PROFILE_PARAM_CLIENT_KEY_PWD
#define SARA_R5_SEC_PROFILE_PARAM_PSK UBLOX_AT_SEC_PROFILE_PARAM_PSK
#define SARA_R5_SEC_PROFILE_PARAM_PSK_IDENT UBLOX_AT_SEC_PROFILE_PARAM_PSK_IDENT
#define SARA_R5_SEC_PROFILE_PARAM_SNI UBLOX_AT_SEC_PROFILE_PARAM_SNI

#define SARA_R5_SEC_PROFILE_CERTVAL_OPCODE_NO UBLOX_AT_SEC_PROFILE_CERTVAL_OPCODE_NO
#define SARA_R5_SEC_PROFILE_CERTVAL_OPCODE_YESNOURL UBLOX_AT_SEC_PROFILE_CERTVAL_OPCODE_YESNOURL
#define SARA_R5_SEC_PROFILE_CERVTAL_OPCODE_YESURL UBLOX_AT_SEC_PROFILE_CERVTAL_OPCODE_YESURL
#define SARA_R5_SEC_PROFILE_CERTVAL_OPCODE_YESURLDATE UBLOX_AT_SEC_PROFILE_CERTVAL_OPCODE_YESURLDATE

#define SARA_R5_SEC_PROFILE_TLS_OPCODE_ANYVER UBLOX_AT_SEC_PROFILE_TLS_OPCODE_ANYVER
#define SARA_R5_SEC_PROFILE_TLS_OPCODE_VER1_0 UBLOX_AT_SEC_PROFILE_TLS_OPCODE_VER1_0
#define SARA_R5_SEC_PROFILE_TLS_OPCODE_VER1_1 UBLOX_AT_SEC_PROFILE_TLS_OPCODE_VER1_1
#define SARA_R5_SEC_PROFILE_TLS_OPCODE_VER1_2 UBLOX_AT_SEC_PROFILE_TLS_OPCODE_VER1_2
#define SARA_R5_SEC_PROFILE_TLS_OPCODE_VER1_3 UBLOX_AT_SEC_PROFILE_TLS_OPCODE_VER1_3

#define SARA_R5_SEC_PROFILE_SUITE_OPCODE_PROPOSEDDEFAULT UBLOX_AT_SEC_PROFILE_SUITE_OPCODE_PROPOSEDDEFAULT

#define SARA_R5_SEC_MANAGER_OPCODE_IMPORT UBLOX_AT_SEC_MANAGER_OPCODE_IMPORT

#define SARA_R5_SEC_MANAGER_ROOTCA UBLOX_AT_SEC_MANAGER_ROOTCA
#define SARA_R5_SEC_MANAGER_CLIENT_CERT UBLOX_AT_SEC_MANAGER_CLIENT_CERT
#define SARA_R5_SEC_MANAGER_CLIENT_KEY UBLOX_AT_SEC_MANAGER_CLIENT_KEY
#define SARA_R5_SEC_MANAGER_SERVER_CERT UBLOX_AT_SEC_MANAGER_SERVER_CERT


// Base SARA-R5 class
class SARA_R5: public UBLOX_AT
{

};

class SARA_R500S: public SARA_R5
{

};

class SARA_R500S_01B: public SARA_R5
{

};

class SARA_R500S_61B: public SARA_R5
{

};

class SARA_R510M8S_61B: public SARA_R5
{

};

class SARA_R510S: public SARA_R5
{

};

#endif